"""Initial migration wedding

Revision ID: 0eacfa6a4150
Revises: 
Create Date: 2024-12-28 00:08:22.415868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eacfa6a4150'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_response', schema=None) as batch_op:
        batch_op.alter_column('name_surname',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('name_surname', schema=None) as batch_op:
        batch_op.alter_column('name_surname',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('name_surname', schema=None) as batch_op:
        batch_op.alter_column('name_surname',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('form_response', schema=None) as batch_op:
        batch_op.alter_column('name_surname',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
