# fly.toml app configuration file generated for doraimarin2025 on 2024-12-07T18:43:41+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'doraimarin2025'
primary_region = 'fra'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[[mounts]]
  source = "app"      # Replace with your volume name
  destination = "/backend_wedding"     # Path inside the app where the volume is mounted

[build]
  builder = "paketobuildpacks/builder:base"
